/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author samug
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        inicio.setEnabled(false);
        this.setTitle("Menu Principal");
        menuA="Inicio";
        menuB="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        inicio = new javax.swing.JButton();
        inventarios = new javax.swing.JButton();
        Reportes = new javax.swing.JButton();
        Pedidos = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        pPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pPanel.setBackground(new java.awt.Color(255, 255, 255));
        pPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setForeground(new java.awt.Color(0, 0, 204));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Bienvenido @Usuario");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("LOGO");

        Titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Titulo.setForeground(new java.awt.Color(240, 240, 240));
        Titulo.setText("Menu principal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        inicio.setBackground(new java.awt.Color(0, 0, 240));
        inicio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inicio.setForeground(new java.awt.Color(240, 240, 240));
        inicio.setText("Inicio");
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });

        inventarios.setBackground(new java.awt.Color(0, 0, 240));
        inventarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inventarios.setForeground(new java.awt.Color(240, 240, 240));
        inventarios.setText("Inventarios");
        inventarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventariosActionPerformed(evt);
            }
        });

        Reportes.setBackground(new java.awt.Color(0, 0, 240));
        Reportes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Reportes.setForeground(new java.awt.Color(240, 240, 240));
        Reportes.setText("Reportes");
        Reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesActionPerformed(evt);
            }
        });

        Pedidos.setBackground(new java.awt.Color(0, 0, 240));
        Pedidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Pedidos.setForeground(new java.awt.Color(240, 240, 240));
        Pedidos.setText("Pedidos");
        Pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidosActionPerformed(evt);
            }
        });

        cerrar.setBackground(new java.awt.Color(0, 0, 240));
        cerrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cerrar.setForeground(new java.awt.Color(240, 240, 240));
        cerrar.setText("Cerrar Sesión");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inventarios, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        pPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 49, 170, 560));

        pPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pPanel2Layout = new javax.swing.GroupLayout(pPanel2);
        pPanel2.setLayout(pPanel2Layout);
        pPanel2Layout.setHorizontalGroup(
            pPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        pPanel2Layout.setVerticalGroup(
            pPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        pPanel.add(pPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 630, 550));

        getContentPane().add(pPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void bloquear(){
        switch(menuB){//desbloquea el boton anterior
            case "Inicio":
                inicio.setEnabled(true);
                break;
            case "Inventarios":
                inventarios.setEnabled(true);
                break;
            case "Reportes":
                Reportes.setEnabled(true);
                break;
            case "Pedidos":
                Pedidos.setEnabled(true);
                break;
            default:
                break;
        }
        switch(menuA){//bloque le boton dle menu actual
            case "Inicio":
                inicio.setEnabled(false);
                Titulo.setText("Menu Principal");
                break;
            case "Inventarios":
                inventarios.setEnabled(false);
                Titulo.setText("Inventarios");
                break;
            case "Reportes":
                Reportes.setEnabled(false);
                Titulo.setText("Reportes");
                break;
            case "Pedidos":
                Pedidos.setEnabled(false);
                Titulo.setText("Pedidos");
                break;
            default:
                break;
        }
    }
    
    private void inventariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventariosActionPerformed
        menuB=menuA;
        menuA="Inventarios";
        bloquear();
        panel1=new Inventarios();//abriendo panel desde la pagina principal
        panel1.setBounds(0, 0, 630, 540);
        pPanel2.removeAll();//quita lo que se tiene en el panel 
        pPanel2.add(panel1);// agrega el nuevo panel
        pPanel2.revalidate();//sin esta linea no se muestarn los ocmponentes internos de panel
        pPanel2.repaint();// no se muestran lo colores de los componentes del panel
    }//GEN-LAST:event_inventariosActionPerformed

    private void ReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesActionPerformed
        menuB=menuA;
        menuA="Reportes";
        bloquear();
        pPanel2.removeAll();
        panel3=new Reportes();
        panel3.setBounds(0,0,630,540);
        pPanel2.add(panel3);
        pPanel2.revalidate();
        pPanel2.repaint();
    }//GEN-LAST:event_ReportesActionPerformed

    private void PedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidosActionPerformed
        menuB=menuA;
        menuA="Pedidos";
        bloquear();
        pPanel2.removeAll();
        panel2=new Pedidos();
        panel2.setBounds(0,0,630,540);
        pPanel2.add(panel2);
        pPanel2.revalidate();
        pPanel2.repaint();
    }//GEN-LAST:event_PedidosActionPerformed

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        menuB=menuA;
        menuA="Inicio";
        bloquear();
        pPanel2.removeAll();
        pPanel2.revalidate();
        pPanel2.repaint();
    }//GEN-LAST:event_inicioActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pedidos;
    private javax.swing.JButton Reportes;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton inicio;
    private javax.swing.JButton inventarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pPanel;
    private javax.swing.JPanel pPanel2;
    // End of variables declaration//GEN-END:variables
    Inventarios panel1;
    Pedidos panel2;
    Reportes panel3;
    String menuA,menuB;//menuA es el menu actual, menuB es el menu anteririor
}
